# ============================================
# logging
# ============================================
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
    compress: "true"
# ============================================
# netwokrs
# ============================================
networks:
  restricted_wan:
    external: true

services:
  # ============================================
  # ollama
  # ============================================
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    logging: *default-logging
    hostname: ollama
    networks:
      restricted_wan:
        ipv4_address: 172.20.30.36
    environment:
      - LOG_LEVEL=info
      - TZ=${TIMEZONE}
      - UMASK_SET=${USER_MASK}
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_MAX_LOADED_MODELS=1
    volumes:
      - ${CONFIG_ROOT:-.}/ollama:/root/.ollama
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ollama.service=ollama"
      - "traefik.http.routers.ollama.tls=true"
      - "traefik.http.routers.ollama.entrypoints=websecure"
      - "traefik.http.routers.ollama.rule=Host(`ollama.${DOMAIN}`)"
      - "traefik.http.services.ollama.loadbalancer.server.port=11434"
      - "traefik.http.routers.ollama.tls.certresolver=cloudflare"
    devices:
      - /dev/dri:/dev/dri
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    security_opt:
      - no-new-privileges:true
    restart: "unless-stopped"
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: "2.0"
  # ============================================
  # openwebui -ai ui
  # ============================================
  openwebui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: openwebui
    logging: *default-logging
    hostname: openwebui
    networks:
      restricted_wan:
        ipv4_address: 172.20.30.34
    environment:
      - LOG_LEVEL=info
      - TZ=${TIMEZONE}
      - UMASK_SET=${USER_MASK}
      - HF_TOKEN=${HF_TOKEN}
      - OLLAMA_BASE_URL=http://172.20.30.36:11434
    volumes:
      - ${CONFIG_ROOT:-.}/openwebui:/app/backend/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.oi.service=oi"
      - "traefik.http.routers.oi.tls=true"
      - "traefik.http.routers.oi.entrypoints=websecure"
      - "traefik.http.routers.oi.rule=Host(`oi.${DOMAIN}`)"
      - "traefik.http.services.oi.loadbalancer.server.port=8080"
      - "traefik.http.routers.oi.tls.certresolver=cloudflare"
    devices:
      - /dev/dri:/dev/dri
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    security_opt:
      - no-new-privileges:true
    restart: "unless-stopped"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://127.0.0.1:8080/health"]
      interval: 1m
      retries: 10
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "2.0"
