services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
      - JELLYFIN_PublishedServerUrl=${HOSTNAME}/jellyfin
    volumes:
      - ${MNT_DATA}/Configs/Jellyfin:/config
      - ${MNT_DATA}/TV:/data/tvshows
      - ${MNT_DATA}/Movies:/data/movies
      - ${MNT_DATA}/Photos:/data/photos
      - ${MNT_DATA}/Music:/data/music
    devices:
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
    ports:
      - 8096:8096
    restart: always

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - ${MNT_DATA}/Configs/Sonarr:/config
      - ${MNT_DATA}/TV:/tv
      - ${MNT_DATA}/Torrents/downloads:/downloads
    ports:
      - 8989:8989
    restart: always

  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    volumes:
      - ${MNT_DATA}/Configs/Jackett:/config
      - ${MNT_DATA}/Torrents/downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9117:9117
    restart: always
  
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - ${MNT_DATA}/Configs/Prowlarr:/config
    ports:
      - 9696:9696
    restart: always

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - ${MNT_DATA}/Configs/Gitea:/etc/gitea
      - ${MNT_DATA}/Gitea:/data
    ports:
      - 3000:3000
      - 2222:22
    restart: always

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - ${MNT_DATA}/Configs/Transmission:/config
      - ${MNT_DATA}/Torrents/downloads:/downloads
      - ${MNT_DATA}/Torrents/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: always

networks:
  default:
    name: docker-compose-nas