services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
      - JELLYFIN_PublishedServerUrl=${HOSTNAME}/jellyfin
    volumes:
      - ${MNT_DATA}/Configs/Jellyfin:/config
      - ${MNT_DATA}/TV:/data/tvshows
      - ${MNT_DATA}/Movies:/data/movies
      - ${MNT_DATA}/Photos:/data/photos
      - ${MNT_DATA}/Music:/data/music
    devices:
       - /dev/vchiq:/dev/qchiq
    ports:
      - 8096:8096
    restart: always

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - ${MNT_DATA}/Configs/Gitea:/etc/gitea
      - ${MNT_DATA}/Gitea:/data
    ports:
      - "3000:3000"
      - "2222:22"
    restart: always

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - ${MNT_DATA}/Configs/Transmission:/config
      - ${MNT_DATA}/Torrents/downloads:/downloads
      - ${MNT_DATA}/Torrents/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: always

networks:
  default:
    name: docker-compose-nas