global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "homeassistant"
    static_configs:
      - targets: ["192.168.88.23:9100"]
  - job_name: "pi-hole"
    static_configs:
      - targets: ["192.168.88.25:9100"]
  - job_name: "home-nas"
    static_configs:
      - targets: ["192.168.88.88:9100"]
  - job_name: mqtt-exporter
    static_configs:
      - targets: ["192.168.88.88:9000"]
