{
 "title": "Prometheus metrics",
 "tags": [ "prometheus" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Time Series", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Time Series Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prometheus_tsdb_head_series", "legendFormat": "total" }
   ]
  },
  {
   "title": "Time Series Created / Deleted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_head_series_created_total[2h])",
     "legendFormat": "Created"
    },
    {
     "expr": "increase(prometheus_tsdb_head_series_removed_total[2h])",
     "legendFormat": "Removed - {{job}}"
    }
   ]
  },
  {
   "title": "Active Time Series Count by Job",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "prometheus_tsdb_head_series", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Prometheus Server Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_http_requests_total[5m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  { "title": "Samples", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Sample Ingestion Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total[5m])",
     "legendFormat": "samples /s"
    }
   ]
  },
  {
   "title": "Byte / Sample Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(rate(prometheus_tsdb_compaction_chunk_size_bytes_sum[1d])) / rate(prometheus_tsdb_compaction_chunk_samples_sum[1d])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Scrape duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "prometheus_target_interval_length_seconds{quantile=\"0.9\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Samples Scrape Count by Job",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(scrape_series_added[5m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}